### ISSUE TITLE
Naming Convention for Image Files

### ISSUE THREAD

**Issue by NiloufarAb** [IS2AI/TFW#1]
Hi Akuzdeuov,

I'm very interested to use this dataset for face recognition applications. Therefore, I need to understand the naming convention that you used for image files. For each image file, there are 6 digits. Could you please let me know what is the rule for naming? 

Thanks,
Niloufar

**Comment by akuzdeuov** [comment]
Hi Niloufar,

The `c-indoor` set was built from our previously published SpeakingFaces dataset (https://www.mdpi.com/1424-8220/21/10/3465/htm). There are two naming conventions:
1) subID_trialID_sessionID_posID_frameID_streamID.png
2) subID_trialID_sessionID_posID_commandID_frameID_streamID.png
- subID = {1 . . . 142} denotes the subject number.
- trialID = {1, 2} denotes the trial number.
- sessionID is 1 if the session does not involve utterances and 2 otherwise.
- posID = {1 . . . 9} denotes the camera position.
- commandID = {1 . . . 297} denotes the command number.
- frameID = {1 . . . 900} the number of an image in a sequence.
- streamID is 1 for thermal images, 2 for visual images, and 3 for the aligned version of the visual images.

The detailed information can be found in the paper (https://www.mdpi.com/1424-8220/21/10/3465/htm). Regarding the `s-indoor` and `u-outdoor` sets, the naming conventions are simply image orders. Thus, they do not contain information about subjects' ids.
